name: Scala CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "nba-information-twitter-bot"
        heroku_email: "ariel.piro@hotmail.com"
        usedocker: false
