name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: heroku deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run sbt stage deployHeroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          sbt stage deployHeroku